import { CheckIcon } from '@heroicons/react/outline';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import useAuth from '../hooks/useAuth';
import TLogo from '../public/tonyflix.png';

function Plans() {

	const { logout } = useAuth();
	return (
		<div>
			<Head>
				<title>Tonyflix - Forfait/Abonnement</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<header className='border-b border-white/40 bg-[#010511]'>
				<Link href='/'>
					<Image
						src={TLogo}
						alt='Tonyflix Logo'
						width={180}
						height={60}
						className='cursor-pointer object-contain'/>
				</Link>
				<button
					className='text-xl font-medium hover:underline'
					onClick={logout}>
                    Se déconnecter
				</button>
			</header>

			<main className='max-w-5xl px-5 pt-36 pb-12 transition-all md:px-10'>
				<h1 className='mb-3 text-3xl font-medium'>Sélectionnez le forfait qui vous convient.</h1>
				<ul>
					<li className="flex items-center gap-x-2 text-lg">
						<CheckIcon className="h-7 w-7 text-[#E50914]" /> Regardez autant que vous voulez. Sans publicité.
					</li>
					<li className="flex items-center gap-x-2 text-lg">
						<CheckIcon className="h-7 w-7 text-[#E50914]" /> Recommendations personnalisées.
					</li>
					<li className="flex items-center gap-x-2 text-lg">
						<CheckIcon className="h-7 w-7 text-[#E50914]" /> Changez ou annulez votre forfait à tout moment.
					</li>
				</ul>

				<div className='mt-4 flex flex-col space-y-4'>
					<div className='flex w-full items-center justify-center self-end md:w-3/5'>
						<div className='planBox'>Essentiel</div>
						<div className='planBox'>Standard</div>
						<div className='planBox'>Premium</div>
					</div>
					<button>Inscription</button>
				</div>

			</main>
		</div>
	);
}

export default Plans;