import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import TLogo from '../public/tonyflix.png';

function Plans() {
	return (
		<div>
			<Head>
				<title>Tonyflix - Forfait/Abonnement</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<header>
				<Link href='/'>
					<Image
						src={TLogo}
						alt='Tonyflix Logo'
						width={150}
						height={50}
						className='cursor-pointer object-contain'/>
				</Link>
			</header>
		</div>
	);
}

export default Plans;