import { CheckIcon } from '@heroicons/react/outline';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import useAuth from '../hooks/useAuth';
import TLogo from '../public/tonyflix.png';

function Plans() {

	const { logout } = useAuth();
	return (
		<div>
			<Head>
				<title>Tonyflix - Forfait/Abonnement</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<header className='border-b border-white/10 bg-[#010511]'>
				<Link href='/'>
					<Image
						src={TLogo}
						alt='Tonyflix Logo'
						width={180}
						height={60}
						className='cursor-pointer object-contain'/>
				</Link>
				<button
					className='text-xl font-medium hover:underline'
					onClick={logout}>
                    Se déconnecter
				</button>
			</header>
			<main className='pt-36'>
				<h1 className='mb-3 text-3xl font-medium'>Sélectionnez le forfait qui vous convient.</h1>
				<ul>
					<li className="flex items-center gap-x-2 text-lg">
						<CheckIcon className="h-7 w-7 text-[#E50914]" /> Regardez autant que vous voulez. Sans publicité.
					</li>
					<li className="flex items-center gap-x-2 text-lg">
						<CheckIcon className="h-7 w-7 text-[#E50914]" /> Recommendations personnalisées.
					</li>
					<li className="flex items-center gap-x-2 text-lg">
						<CheckIcon className="h-7 w-7 text-[#E50914]" /> Changez ou annulez votre forfait à tout moment.
					</li>
				</ul>
			</main>
		</div>
	);
}

export default Plans;