/* eslint-disable react/no-unescaped-entities */
import Head from 'next/head';
import Header from '../components/Header';

function Custom404() {
	return (
		<div>
			<Head>
				<title>Tonyflix - Erreur 404</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Header />
			<h1 className='text-center w-screen py-36'>Oops, cette page n'existe pas</h1>
		</div>
	);
}

export default Custom404;