import Head from 'next/head';
import Header from '../components/Header';
import Image from 'next/image';
import Travolta from '../public/travolta.gif';

function Custom404() {
	return (
		<div>
			<Head>
				<title>Tonyflix - Erreur 404</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Header />
			<h1 className='text-center w-screen pt-48 font-bold md:text-4xl sm:text-2xl text-xl'>Oops, John Travolta a perdu votre page :(</h1>
			<div className='text-center w-screen'>
				<Image
					src={Travolta}
					alt='404 Travolta'
					width={800}
					height={800}
					className='object-contain'/>
			</div>
		</div>
	);
}

export default Custom404;