import Head from 'next/head';
import Image from 'next/image';
import TLogo from '../public/tonyflix.png';
import Link from 'next/link';
import Account from '../public/account3.png';

function account() {
	return (
		<div>
			<Head>
				<title>Tonyflix - Compte</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<header>
				<Link href='/'>
					<Image
						src={TLogo}
						alt='Tonyflix Logo'
						width={150}
						height={50}
						className='cursor-pointer object-contain'/>
				</Link>
				<Link href='/account'>
					<Image src={Account}
						alt='Account Logo'
						width={50}
						height={50}
						className='cursor-pointer rounded'/>
				</Link>
			</header>
		</div>
	);
}

export default account;