import Head from 'next/head';
import Image from 'next/image';
import BackgroundLogin from '../public/netflix-background.jpg';
import TLogo from '../public/tonyflix.png';
import { useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { ChevronRightIcon } from '@heroicons/react/outline';

const Home = () => {

	const [email, setEmail] = useState('');
	const router = useRouter();

	const onSubmitForm = (event: { preventDefault: () => void }) => {
		event.preventDefault();
		if (email) {
			router.push('/subscription');
		} else {
			alert('Veuillez rentrer une adresse e-mail correcte');
		}
	};

	return (
		<div className='relative flex h-screen w-screen flex-col bg-[#010511] md:items-center md:justify-center md:bg-transparent'>
			<Head>
				<title>Tonyflix - Accueil</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Image
				src={BackgroundLogin}
				alt='Tonyflix Login Background'
				layout='fill'
				objectFit='cover'
				className='-z-10 !hidden opacity-60 sm:!inline'
			/>
			<div className='absolute left-4 top-4 md:left-10 md:top-6 lg:w-72 md:w-72 sm:w-44 vsm:w-44'>
				<Image
					src={TLogo}
					alt='Tonyflix Logo'
					width={300}
					height={150}
					className='cursor-pointer object-contain'/>
			</div>
			<div className='absolute right-12 top-10'>
				<Link href='/login'>
					<button className='bg-[#e50914] py-2 px-3 font-medium text-white rounded text-base cursor-pointer'>S&apos;identifier</button>
				</Link>
			</div>
			<div className='w-full absolute lg:top-50 sm:top-60 vsm:top-60 left-0 flex flex-col items-center justify-center text-white'>
				<h1 className='lg:text-7xl sm:text-6xl vsm:text-5xl font-bold lg:w-[calc(100%/2)] sm:w-[calc(100%/1.5)] vsm:w-[calc(100%/1.2)] text-center mb-8'>Films, séries TV et bien plus en illimité.</h1>
				<h2 className='lg:text-3xl sm:text-2xl vsm:text-2xl font-medium vsm:w-[calc(100%/1.2)] text-center mb-10'>Où que vous soyez. Annulez à tout moment.</h2>
				<p className='lg:text-2xl sm:text-1.5xl vsm:text-1.5xl font-medium w-[calc(100%/1.8)] sm:w-[calc(100%/1.5)] vsm:w-[calc(100%/1.2)] text-center mb-5'>
					Prêt à regarder Tonyflix ? Saisissez votre adresse e-mail pour vous abonner ou réactiver votre abonnement.
				</p>
				<form
					className='lg:w-6/12 vsm:w-10/12 bg-white text-gray-600 flex items-center justify-between mt-5 h-16 rounded'
					onSubmit={onSubmitForm}>
					<input
						className='w-6/12 border-none focus:border-none focus:ring-white'
						type='email'
						placeholder='Adresse e-mail'
						onChange={(event) => setEmail(event.target.value)}
						value={email}/>
					<button type='submit' className='h-full bg-[#e50914] text-white text-3xl font-medium cursor-pointer px-7 items-center hidden lg:flex'>
						Commencer
						<ChevronRightIcon className='h-9 w-9 ml-3' />
					</button>
					<button
						type='submit'
						className='h-full w-40 bg-[#e50914] text-white py-3 font-medium flex justify-center items-center text-xl lg:hidden'
					>
					Commencer<ChevronRightIcon className='h-6 w-6 ml-2' />
					</button>
				</form>
			</div>
		</div>
	);
};

export default Home;
