import Head from 'next/head';
import Image from 'next/image';
import BackgroundLogin from '../public/netflix-background.jpg';
import TLogo from '../public/tonyflix.png';

function Login() {
	return (
		<div className='relative flex h-screen w-screen flex-col bg-[#010511] md:items-center md:justify-center md:bg-transparent'>
			<Head>
				<title>Tonyflix - Connexion</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Image
				src={BackgroundLogin}
				alt="Tonyflix Login Background"
				layout='fill'
				objectFit='cover'
				className='-z-10 !hidden opacity-60 sm:!inline'
			/>
			<div className='absolute left-4 top-4 md:left-10 md:top-6'>
				<Image
					src={TLogo}
					alt="Tonyflix Logo"
					width={300}
					height={150}
					className='cursor-pointer object-contain'/>
			</div>
		</div>
	);
}

export default Login;