import Head from 'next/head';
import Header from '../components/Header';
import SearchBar from '../components/SearchBar';

function search() {
	return (
		<div className='relative h-screen bg-gradient-to-b from-gray-900/10 to-[#010511] lg:h-[140vh]'>
			<Head>
				<title>Tonyflix - Rechercher Séries Ou Films</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Header />
			<div className='pt-24 lg:space-y-24 px-16 grid justify-items-center'>
				<SearchBar />
			</div>
		</div>
	);
}

export default search;