import { SearchIcon } from '@heroicons/react/outline';
import Head from 'next/head';
import Header from '../components/Header';

function search() {
	return (
		<div className='relative h-screen bg-gradient-to-b from-gray-900/10 to-[#010511] lg:h-[140vh]'>
			<Head>
				<title>Tonyflix - Rechercher Séries Ou Films</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Header />
			<main className='relative pl-4 pt-24 lg:space-y-24 lg:pl-16'>
				<h2>Search Page</h2>
				<div className='text-center'>
					<SearchIcon className='hidden h-6 w-6 sm:inline' />
					<button
						type='submit'
						placeholder='Rechercher votre série ou film'>
					</button>
				</div>
			</main>
		</div>
	);
}

export default search;