import Head from 'next/head';
import Banner from '../components/Banner';
import Header from '../components/Header';
import Row from '../components/Row';
import { Movie } from '../typing';
import requests from '../utils/requests';

type Props = {
	popularTVShows: Movie[],
	topRatedTVShows: Movie[],
	actionAndAdventureTVShows: Movie[],
	comedyTVShows: Movie[],
	animationTVShows: Movie[],
	documentaryTVShows: Movie[],
	romanceTVShows: Movie[],
	thrillerTVShows: Movie[],
	sciFiAndFantasticTVShows: Movie[],
	dramaTVShows: Movie[],
	kidsTVShows: Movie[],
	mysteryTVShows: Movie[],
	soapTVShows: Movie[],
};

export const getServerSideProps = async () => {
	try {
		const [
			popularTVShows,
			topRatedTVShows,
			actionAndAdventureTVShows,
			comedyTVShows,
			animationTVShows,
			documentaryTVShows,
			romanceTVShows,
			thrillerTVShows,
			sciFiAndFantasticTVShows,
			dramaTVShows,
			kidsTVShows,
			mysteryTVShows,
			soapTVShows,
		] = await Promise.all([
			fetch(requests.fetchPopularTVShows).then((results) => results.json()),
			fetch(requests.fetchTopRatedTVShows).then((results) => results.json()),
			fetch(requests.fetchActionAndAdventureTVShows).then((results) => results.json()),
			fetch(requests.fetchComedyTVShows).then((results) => results.json()),
			fetch(requests.fetchAnimationTVShows).then((results) => results.json()),
			fetch(requests.fetchDocumentaryTVShows).then((results) => results.json()),
			fetch(requests.fetchRomanceTVShows).then((results) => results.json()),
			fetch(requests.fetchThrillerTVShows).then((results) => results.json()),
			fetch(requests.fetchSciFiAndFantasticTVShows).then((results) => results.json()),
			fetch(requests.fetchDramaTVShows).then((results) => results.json()),
			fetch(requests.fetchKidsTVShows).then((results) => results.json()),
			fetch(requests.fetchMysteryTVShows).then((results) => results.json()),
			fetch(requests.fetchSoapTVShows).then((results) => results.json()),
		]);
		return {
			props: {
				popularTVShows: popularTVShows.results,
				topRatedTVShows: topRatedTVShows.results,
				actionAndAdventureTVShows: actionAndAdventureTVShows.results,
				comedyTVShows: comedyTVShows.results,
				animationTVShows: animationTVShows.results,
				documentaryTVShows: documentaryTVShows.results,
				romanceTVShows: romanceTVShows.results,
				thrillerTVShows: thrillerTVShows.results,
				sciFiAndFantasticTVShows: sciFiAndFantasticTVShows.results,
				dramaTVShows: dramaTVShows.results,
				kidsTVShows: kidsTVShows.results,
				mysteryTVShows: mysteryTVShows.results,
				soapTVShows: soapTVShows.results,
			},
		};

	} catch (error) {
		console.trace(error);
	}
};

function tvshows({
	popularTVShows,
	topRatedTVShows,
	actionAndAdventureTVShows,
	comedyTVShows,
	animationTVShows,
	documentaryTVShows,
	romanceTVShows,
	thrillerTVShows,
	sciFiAndFantasticTVShows,
	dramaTVShows,
	kidsTVShows,
	mysteryTVShows,
	soapTVShows,
}: Props) {
	return (
		<div className='relative h-screen bg-gradient-to-b from-gray-900/10 to-[#010511] lg:h-[140vh]'>
			<Head>
				<title>Tonyflix - Séries</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Header />
			<main className='relative pl-4 pb-24 lg:space-y-24 lg:pl-16'>
				<Banner bannerData={popularTVShows} />
				<section className='md:space-y-24'>
					<Row title='Populaires' movies={popularTVShows}/>
					<Row title='Les mieux notés' movies={topRatedTVShows}/>
					<Row title='Action/Aventure' movies={actionAndAdventureTVShows}/>
					<Row title='Animation' movies={animationTVShows}/>
					<Row title='Thriller' movies={thrillerTVShows}/>
					<Row title='Fantastique' movies={sciFiAndFantasticTVShows}/>
					<Row title='Drame' movies={dramaTVShows}/>
					<Row title='Comédie' movies={comedyTVShows}/>
					<Row title='Kids' movies={kidsTVShows}/>
					<Row title='Mystère' movies={mysteryTVShows}/>
					<Row title='Documentaire' movies={documentaryTVShows}/>
					<Row title='Romance' movies={romanceTVShows}/>
					<Row title='Soap' movies={soapTVShows}/>
				</section>
			</main>
		</div>
	);
}

export default tvshows;